/**
https://theme-hope.vuejs.press/zh/config/theme/layout.html
手动写算了，不好控制排序
*/
export const onNewSidebar = () => {
 return [
    {
        text:"🌏安装",
        children:[
            {
                text:"Chrome浏览器安装",
                link:"/cn/install/chrome"
            },
            {
                text:"Edge浏览器安装",
                link:"/cn/install/edge"
            },
            {
                text:"Firefox浏览器安装",
                link:"/cn/install/firefox"
            },
            {
                text:"360极速浏览器安装",
                link:"/cn/install/360"
            },
            {
                text:"Safari浏览器",
                link:"/cn/install/safari"
            },
            {
                text:"其他浏览器安装",
                link:"/cn/install/other"
            }
        ]
    },
    {
        text:"🤏关于我们",
        children:[
            {
                text:"为什么要做Etab",
                link:"/cn/about/why"
            },
            {
                text:"内容合作",
                link:"/cn/about/cooperate"
            },
            {
                text:"关注我们",
                link:"/cn/about/about"
            },
            {
                text:"特别鸣谢",
                link:"/cn/about/thank"
            },
        ]
    },
    {
        text:"🤞使用帮助",
        children:[
            {
                text:"社区讨论",
                link:"/cn/help/skills"
            },
            {
                text:"常见问题",
                link:"/cn/help/faq"
            },
            {
                text:"使用技巧",
                link:"/cn/help/community"
            }
        ]
    },
    {
        text:"🔐服务协议",
        children:[
            {
                text:"隐私政策",
                link:"/cn/serves/privacy"
            },
            {
                text:"免责声明",
                link:"/cn/serves/disclaimer"
            },
        ]
    },
 ]
}